package com.sdx.common.entity;

import java.util.Date;

public class ClientLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_log.log_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_log.request_content
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private String requestContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_log.resposne_content
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private String resposneContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_log.request_time
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private Date requestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_log.client_type
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private String clientType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_log.log_id
     *
     * @return the value of client_log.log_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_log.log_id
     *
     * @param logId the value for client_log.log_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_log.request_content
     *
     * @return the value of client_log.request_content
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public String getRequestContent() {
        return requestContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_log.request_content
     *
     * @param requestContent the value for client_log.request_content
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setRequestContent(String requestContent) {
        this.requestContent = requestContent == null ? null : requestContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_log.resposne_content
     *
     * @return the value of client_log.resposne_content
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public String getResposneContent() {
        return resposneContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_log.resposne_content
     *
     * @param resposneContent the value for client_log.resposne_content
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setResposneContent(String resposneContent) {
        this.resposneContent = resposneContent == null ? null : resposneContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_log.request_time
     *
     * @return the value of client_log.request_time
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_log.request_time
     *
     * @param requestTime the value for client_log.request_time
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_log.client_type
     *
     * @return the value of client_log.client_type
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_log.client_type
     *
     * @param clientType the value for client_log.client_type
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }
}