package com.sdx.common.entity;

import java.util.Date;

public class MiddLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midd_log.log_id
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midd_log.reqNo
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    private String reqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midd_log.content
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midd_log.url
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midd_log.result
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column midd_log.create_tile
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    private Date createTile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midd_log.log_id
     *
     * @return the value of midd_log.log_id
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midd_log.log_id
     *
     * @param logId the value for midd_log.log_id
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midd_log.reqNo
     *
     * @return the value of midd_log.reqNo
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public String getReqno() {
        return reqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midd_log.reqNo
     *
     * @param reqno the value for midd_log.reqNo
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public void setReqno(String reqno) {
        this.reqno = reqno == null ? null : reqno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midd_log.content
     *
     * @return the value of midd_log.content
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midd_log.content
     *
     * @param content the value for midd_log.content
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midd_log.url
     *
     * @return the value of midd_log.url
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midd_log.url
     *
     * @param url the value for midd_log.url
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midd_log.result
     *
     * @return the value of midd_log.result
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midd_log.result
     *
     * @param result the value for midd_log.result
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column midd_log.create_tile
     *
     * @return the value of midd_log.create_tile
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public Date getCreateTile() {
        return createTile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column midd_log.create_tile
     *
     * @param createTile the value for midd_log.create_tile
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    public void setCreateTile(Date createTile) {
        this.createTile = createTile;
    }
}