package com.sdx.common.entity;

public class UserBind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind.bind_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private Integer bindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind.uid
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bind.weixin_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    private String weixinId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind.bind_id
     *
     * @return the value of user_bind.bind_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public Integer getBindId() {
        return bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind.bind_id
     *
     * @param bindId the value for user_bind.bind_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setBindId(Integer bindId) {
        this.bindId = bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind.uid
     *
     * @return the value of user_bind.uid
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind.uid
     *
     * @param uid the value for user_bind.uid
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bind.weixin_id
     *
     * @return the value of user_bind.weixin_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public String getWeixinId() {
        return weixinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bind.weixin_id
     *
     * @param weixinId the value for user_bind.weixin_id
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    public void setWeixinId(String weixinId) {
        this.weixinId = weixinId == null ? null : weixinId.trim();
    }
}