package com.sdx.common.mapper;

import com.sdx.common.entity.ClientLog;
import com.sdx.common.entity.ClientLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int countByExample(ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int deleteByExample(ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int insert(ClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int insertSelective(ClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    List<ClientLog> selectByExample(ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    ClientLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int updateByExampleSelective(@Param("record") ClientLog record, @Param("example") ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int updateByExample(@Param("record") ClientLog record, @Param("example") ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int updateByPrimaryKeySelective(ClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated Sun Jun 28 14:22:49 CST 2015
     */
    int updateByPrimaryKey(ClientLog record);
}