package com.sdx.common.mapper;

import com.sdx.common.entity.MiddLog;
import com.sdx.common.entity.MiddLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiddLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int countByExample(MiddLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int deleteByExample(MiddLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int insert(MiddLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int insertSelective(MiddLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    List<MiddLog> selectByExample(MiddLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    MiddLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") MiddLog record, @Param("example") MiddLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int updateByExample(@Param("record") MiddLog record, @Param("example") MiddLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int updateByPrimaryKeySelective(MiddLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table midd_log
     *
     * @mbggenerated Sat Jun 27 00:58:10 CST 2015
     */
    int updateByPrimaryKey(MiddLog record);
}