package com.sdx.common.mapper;

import com.sdx.common.entity.UserBind;
import com.sdx.common.entity.UserBindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int countByExample(UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int deleteByExample(UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int deleteByPrimaryKey(Integer bindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int insert(UserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int insertSelective(UserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    List<UserBind> selectByExample(UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    UserBind selectByPrimaryKey(Integer bindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserBind record, @Param("example") UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int updateByExample(@Param("record") UserBind record, @Param("example") UserBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int updateByPrimaryKeySelective(UserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bind
     *
     * @mbggenerated Sun Jun 21 23:34:49 CST 2015
     */
    int updateByPrimaryKey(UserBind record);
}